export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SIGNUP = "AUTH_SIGNUP";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_FORGOT_PASSWORD = "AUTH_FORGOT_PASSWORD";
export const AUTH_PASSWORD_RESET = "AUTH_PASSWORD_RESET";
export const AUTH_COMPLETE_QUICKPAY_REGISTRATION = "AUTH_COMPLETE_QUICKPAY_REGISTRATION";