export const BAMBORA_PAYMENT_REQUEST = "BAMBORA_PAYMENT_REQUEST";
export const BAMBORA_TOKEPAY_REQUEST = "BAMBORA_TOKEPAY_REQUEST";
export const BAMBORA_QUICK_PAYMENT_REQUEST = "BAMBORA_QUICK_PAYMENT_REQUEST";
export const BAMBORA_UPDATE_BALANCE = "BAMBORA_UPDATE_BALANCE";