export const USER_REQUEST = "USER_REQUEST";
export const USER_VERIFY = "USER_VERIFY";
export const USER_SEND_VERIFICATION_CODE = "USER_SEND_VERIFICATION_CODE";
export const USER_NAME_LOOKUP = "USER_NAME_LOOKUP";
export const USER_GET_TRANSACTIONS = "USER_GET_TRANSACTIONS";
